CREATE TABLE NOTOWANIA (
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOTOWANIA VARCHAR(5) NOT NULL, 
DATA_KURSU DATE NOT NULL,
OTWARCIE DOUBLE NOT NULL,
MAKSIMUM DOUBLE NOT NULL,
MINIMUM DOUBLE NOT NULL,
ZAMKNIECIE DOUBLE NOT NULL,
MOD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)