CREATE TABLE KOMUNIKATY (
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_SPOLKA INT(4) NOT NULL, 
DATA_KOM DATETIME NOT NULL,
TRESC VARCHAR(1000) NOT NULL,
LINK_CALOSC VARCHAR(500) NOT NULL,
MOD_TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)
